export const GET_ALL_ADMIN_REQUEST = 'GET_ALL_ADMIN_REQUEST';
export const GET_ALL_ADMIN_SUCCESS = 'GET_ALL_ADMIN_SUCCESS';
export const GET_ALL_ADMIN_FAILURE = 'GET_ALL_ADMIN_FAILURE';

export const ADD_ADMIN_REQUEST = 'ADD_ADMIN_REQUEST';
export const ADD_ADMIN_SUCCESS = 'ADD_ADMIN_SUCCESS';
export const ADD_ADMIN_FAILURE = 'ADD_ADMIN_FAILURE';

export const DELETE_SINGLE_ADMIN_REQUEST = 'DELETE_SINGLE_ADMIN_REQUEST';
export const DELETE_SINGLE_ADMIN_SUCCESS = 'DELETE_SINGLE_ADMIN_SUCCESS';
export const DELETE_SINGLE_ADMIN_FAILURE = 'DELETE_SINGLE_ADMIN_FAILURE'