export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';

export const GET_SINGLE_ARTICLES_SUCCESS = 'GET_SINGLE_ARTICLES_SUCCESS';
export const GET_SINGLE_ARTICLES_REQUEST = 'GET_SINGLE_ARTICLES_REQUEST';
export const GET_SINGLE_ARTICLES_FAILURE = 'GET_SINGLE_ARTICLES_FAILURE';


export const ARTICLE_TYPE_UPDATE_SUCCESS = 'ARTICLE_TYPE_UPDATE_SUCCESS';
export const ARTICLE_TYPE_UPDATE_REQUEST = 'ARTICLE_TYPE_UPDATE_REQUEST';
export const ARTICLE_TYPE_UPDATE_FAILURE = 'ARTICLE_TYPE_UPDATE_FAILURE';

export const PUBLISH_MESSAGE_SUCCESS = 'PUBLISH_MESSAGE_SUCCESS';
export const PUBLISH_MESSAGE_REQUEST = 'PUBLISH_MESSAGE_REQUEST';
export const PUBLISH_MESSAGE_FAILURE = 'PUBLISH_MESSAGE_FAILURE';

export const REJECT_ARTICLE_SUCCESS = 'REJECT_ARTICLE_SUCCESS';
export const REJECT_ARTICLE_REQUEST = 'REJECT_ARTICLE_REQUEST';
export const REJECT_ARTICLE_FAILURE = 'REJECT_ARTICLE_FAILURE';