export const GET_ALL_QUERIES_REQUEST = 'GET_ALL_QUERIES_REQUEST';
export const GET_ALL_QUERIES_SUCCESS = 'GET_ALL_QUERIES_SUCCESS';
export const GET_ALL_QUERIES_FAILURE = 'GET_ALL_QUERIES_FAILURE';

export const UPDATE_QUERIES_REQUEST = 'UPDATE_QUERIES_REQUEST';
export const UPDATE_QUERIES_SUCCESS = 'UPDATE_QUERIES_SUCCESS';
export const UPDATE_QUERIES_FAILURE = 'UPDATE_QUERIES_FAILURE';


export const DELETE_SINGLE_QUERY_REQUEST = 'DELETE_SINGLE_QUERY_REQUEST';
export const DELETE_SINGLE_QUERY_SUCCESS = 'DELETE_SINGLE_QUERY_SUCCESS';
export const DELETE_SINGLE_QUERY_FAILURE = 'DELETE_SINGLE_QUERY_FAILURE';

export const GET_SINGLE_QUERY_REQUEST = 'GET_SINGLE_QUERY_REQUEST';
export const GET_SINGLE_QUERY_SUCCESS = 'GET_SINGLE_QUERY_SUCCESS';
export const GET_SINGLE_QUERY_FAILURE = 'GET_SINGLE_QUERY_FAILURE';