export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// --------------------User Update--------------------------
export const UPDATE_SINGLE_USER_SUCCESS = 'UPDATE_SINGLE_USER_SUCCESS';
export const UPDATE_SINGLE_USER_REQUEST = 'UPDATE_SINGLE_USER_REQUEST';
export const UPDATE_SINGLE_USER_FAILURE = 'UPDATE_SINGLE_USER_FAILURE';

// =================DELETE SINGLE USER===============================
export const DELETE_SINGLE_USER_SUCCESS = 'DELETE_SINGLE_USER_SUCCESS';
export const DELETE_SINGLE_USER_REQUEST = 'DELETE_SINGLE_USER_REQUEST';
export const DELETE_SINGLE_USER_FAILURE = 'DELETE_SINGLE_USER_FAILURE';